# Generated by Django 4.1.2 on 2022-10-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('author', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('avatar', models.TextField()),
                ('email', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
